### ISSUE TITLE
Nexus positions need updating

### ISSUE THREAD

**Issue by gcruice** [thomas-crane/famebot#35] opened 2017-10-25 21:56 UTC
A new update was released with an updated nexus.

**Comment by thomas-crane** [comment] 2017-10-25 22:11
If you have the latest version from either MPGH or GitHub you should be able to fix this yourself by using some commands:

1. Stand in a position where you are being healed by the fountains and use the command `/famebot set fountainposition`
2. Stand in a position where all of the realms are visible and there is a clear path from the spawn point to where you are standing and use the command `/famebot set realmposition`
3. Restart the bot and it will now be using the positions you just set.

**Comment by gcruice** [comment] 2017-10-25 22:12
So I did that but every so often it decides to run into one of the corners. Not sure what's causing it to need me to reset the positions though.

**Comment by thomas-crane** [comment] 2017-10-25 22:15
Did you restart the bot fully (e.g. close KRelay and then open it again)?

**Comment by gcruice** [comment] 2017-10-25 22:16
I will make sure to try that. Closing issue for now. If it starts acting up will reopen.

**Comment by gcruice** [comment] 2017-10-25 22:22
So I did this and it worked. But, after I change settings in the famebot it resets the realm and fountain positions

**Comment by thomas-crane** [comment] 2017-10-26 00:44
Thanks for the info, I will fix this soon

**Comment by thomas-crane** [comment] 2017-10-26 01:04
Closing this now since I've implemented a fix and can't reproduce the issue anymore. Please Make a new issue if there are any more config problems.

**Closed by thomas-crane** 2017-10-26 01:04 UTC
