### ISSUE TITLE
Crashes Often

### ISSUE THREAD

**Issue by AzukiMPGH** [thomas-crane/famebot#8] opened 2017-03-23 13:16 UTC
Often time it just crashes right out of the blue. Most of the times this happens when just farming fame, and not actually trying to escape from escape or something.

**Comment by AlanBaumgartner** [comment] 2017-03-23 15:11
Is this krelay crashing or just the famebot stopping?

**Comment by iObsidian** [comment] 2017-03-23 15:43
I had the same problem and it was K-Relay crashing, maybe a conflict
between two plugins

2017-03-23 8:11 GMT-07:00 Alan Baumgartner <notifications@github.com>:

**Comment by AzukiMPGH** [comment] 2017-03-23 15:54
For me it's not K-Relay, it's the actual plugin itself.

**Comment by AlanBaumgartner** [comment] 2017-03-23 20:43
I found that krelay crashed often when I was using my keyboard. Mostly when I was using shift, control, and alt.

**Comment by thomas-crane** [comment] 2017-03-23 21:24
I will have to check this out tomorrow when I'm back at my main computer. Considering that there has also been an update to realm, and that enemy avoidance and several other useful features are implemented or on the horizon, I think I will work on it for a day when I'm back and then make a new release thread on MPGH.

**Comment by thomas-crane** [comment] 2017-03-25 11:41
I'm reluctant to close this because a few people have been reporting it but I can't get it to crash even after having it open for 30 min to 1 hour. There are a few exceptions which happen in KRelay which I will investigate but these don't cause a crash for me. Occasionally the flash player crashes but that may or may not be related to the plugin.

**Comment by AzukiMPGH** [comment] 2017-03-25 12:21
For some reason this has been happening less on my side aswell.

**Comment by AlanBaumgartner** [comment] 2017-03-26 01:22
My flash player crashes still and so does krelay, I am not sure what the causes are but it seems everything crashes but never all at the same time.

**Comment by thomas-crane** [comment] 2017-03-26 02:25
Hopefully with the last few commits the plugin will crash less frequently or not at all. It's hard to test this since I seem to only get crashes after running the bot for 1 hour or more

**Comment by AzukiMPGH** [comment] 2017-03-26 17:40
I might've found a hint to what might be causing the sudden crashes within the plugin itself.
I removed the logging code that would log stuff into the textbox on the form, and then the bot ran fine; hours on end, without crashing a single time.

**Comment by thomas-crane** [comment] 2017-03-26 22:28
Finally some insight! Thanks so much @AzukiMPGH I'll check this out tonight.

**Comment by thomas-crane** [comment] 2017-03-27 21:04
Thanks @AzukiMPGH for finding the cause of this. Closing this because it's now fixed, but I'll open another issue about replacing the logging system

**Closed by thomas-crane** 2017-03-27 21:04 UTC
