### ISSUE TITLE
Nexus changed now it just goes to corner of nexus please fix

### ISSUE THREAD

**Issue by Anshman200** [thomas-crane/famebot#31] opened 2017-07-29 16:57 UTC

**Comment by thomas-crane** [comment] 2017-07-30 22:14
Thanks, will fix this tonight after work.

**Comment by thomas-crane** [comment] 2017-08-01 06:31
Just checked the bot with the latest version of the client and it is still working fine. Are you sure you are using the most up to date version of the bot?
Closing this because I can't reproduce it. If it's still an issue for you just re-download the bot again.

**Closed by thomas-crane** 2017-08-01 06:31 UTC
