### ISSUE TITLE
If the bot reconnect's to a same dungeon > kicked to char list.

### ISSUE THREAD

**Issue by Ninjin89** [thomas-crane/famebot#43] opened 2018-01-13 21:31 UTC
So if you start the bot he walks normal to dungeon and is joining it.
If you go back to Nexus and he walks to same realm again and tries to enter you get kicked to your char list.

Just wanted to mention this here. (Using it with your latest K-Relay release).

**Comment by thomas-crane** [comment] 2018-01-14 08:36
Thanks, will take a look at this now.

**Comment by thomas-crane** [comment] 2018-01-14 09:30
This is actually caused by an issue in KRelay. It's been fixed in thomas-crane/krelay@0642868efb90a4f9b493bfba94221de236b2e62c

Tested and working.

**Closed by thomas-crane** 2018-01-14 09:30 UTC
