### ISSUE TITLE
Krelay Issue

### ISSUE THREAD

**Issue by icedude27** [thomas-crane/famebot#20] opened 2017-05-05 20:16 UTC
Im having an issue with the client.

[Listener]       Starting local listener...
[Listener]       Local listener started.
[Listener]       Stopping local listener...
[Error]          An exception was thrown
within LocalConnect 
at <>c__DisplayClass31_0.<LocalConnect>b__0

Object reference not set to an instance of an object.

The krelay cant find my adobe flash projector client and it won;t let me use any plugins such as famebot. Could you help me out? thanks.

**Comment by thomas-crane** [comment] 2017-05-08 08:18
Are you using any other plugins at the same time as the famebot? I can't reproduce this and couldn't find any potential null reference exceptions either.

**Comment by thomas-crane** [comment] 2017-06-06 00:02
Closing this now since the issue hasn't been reported again since it was first mentioned here.

**Closed by thomas-crane** 2017-06-06 00:02 UTC
