### ISSUE TITLE
[Typo] README.md

### ISSUE THREAD

**Issue by AzukiMPGH** [thomas-crane/famebot#16] opened 2017-04-22 17:41 UTC
![vivaldi_2017-04-22_19-40-18](https://cloud.githubusercontent.com/assets/10087856/25306743/b6c3290e-2793-11e7-98bd-eaad22dbd7f2.png)

**Comment by ZackTaylor** [comment] 2017-04-22 21:44
I'll take care of this @AzukiMPGH.

**Comment by thomas-crane** [comment] 2017-04-23 10:46
Thanks, @ZackTaylor. PR has been merged so the issue is fixed.

**Closed by thomas-crane** 2017-04-23 10:46 UTC
